# HelmRelease definition
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  releaseName: vault
  interval: 1m
  chart:
    spec:
      chart: vault
      version: 0.29.0
      sourceRef:
        kind: HelmRepository
        name: vault  # This should match the HelmRepository name
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: vault-values