# HelmRelease definition
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  releaseName: jenkins
  interval: 1m
  chart:
    spec:
      chart: jenkins-operator
      version: 0.8.1
      sourceRef:
        kind: HelmRepository
        name: jenkins  # This should match the HelmRepository name
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: jenkins-values