all:
  hosts:
    k8s-master-node-1:
      ansible_host: 192.168.1.10
      ip: 192.168.1.10
      access_ip: 192.168.1.10
    k8s-master-node-2:
      ansible_host: 192.168.1.11
      ip: 192.168.1.11
      access_ip: 192.168.1.11
    k8s-master-node-3:
      ansible_host: 192.168.1.12
      ip: 192.168.1.12
      access_ip: 192.168.1.12
    k8s-worker-node-1:
      ansible_host: 192.168.1.20
      ip: 192.168.1.20
      access_ip: 192.168.1.20
    k8s-worker-node-2:
      ansible_host: 192.168.1.21
      ip: 192.168.1.21
      access_ip: 192.168.1.21
    k8s-worker-node-3:
      ansible_host: 192.168.1.22
      ip: 192.168.1.22
      access_ip: 192.168.1.22
    k8s-worker-node-4:
      ansible_host: 192.168.1.23
      ip: 192.168.1.23
      access_ip: 192.168.1.23
    k8s-worker-node-5:
      ansible_host: 192.168.1.24
      ip: 192.168.1.24
      access_ip: 192.168.1.24
  children:
    kube_control_plane:
      hosts:
        k8s-master-node-1:
        k8s-master-node-2:
        k8s-master-node-3:
    kube_node:
      hosts:
        k8s-master-node-1:
        k8s-master-node-2:
        k8s-master-node-3:
        k8s-worker-node-1:
        k8s-worker-node-2:
        k8s-worker-node-3:
        k8s-worker-node-4:
        k8s-worker-node-5:
    etcd:
      hosts:
        k8s-master-node-1:
        k8s-master-node-2:
        k8s-master-node-3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
