# HelmRelease definition
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-subdir-external-provisioner
spec:
  releaseName: nfs-subdir-external-provisioner
  interval: 1m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner  # This should match the HelmRepository name
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: nfs-subdir-external-provisioner-values