apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-subdir-external-provisioner-values
  namespace: nfs-subdir-external-provisioner
data:
  values.yaml: |
    image:
      repository: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
      tag: v4.0.2
      pullPolicy: IfNotPresent
    nfs:
      mountOptions:
      - vers=4.1
      - noresvport
      - nolock
      path: /mnt/test-pool/test-nfs
      server: 10.101.56.230
    podSecurityPolicy:
      enabled: false
    rbac:
      create: true
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    serviceAccount:
      create: true
      name: nfs-client-provisioner
    storageClass:
      accessModes: ReadWriteMany
      allowVolumeExpansion: true
      annotations:
        storageclass.kubernetes.io/is-default-class: "false"
      defaultClass: false
      name: nfs-client
      pathPattern: ${.PVC.namespace}/${.PVC.name}
      reclaimPolicy: Retain
