# HelmRelease definition
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  releaseName: redis
  interval: 1m
  chart:
    spec:
      chart: redis
      version: 20.6.3
      sourceRef:
        kind: HelmRepository
        name: bitnami  # This should match the HelmRepository name
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: redis-values